### ISSUE TITLE
Add new classes from the specification

### ISSUE THREAD

**Issue by TysonAndre** [felixfbecker/php-language-server-protocol#4]
I noticed that some of these are missing, but are mentioned in https://microsoft.github.io/language-server-protocol/specification :

- TextDocumentSyncOptions (ServerCapabilities->textDocumentSync can be an instance of this)
- MarkupContent

**Comment by felixfbecker** [comment]
Yes, I created the classes a long time ago, since then many new types were added - if you need them, PRs welcome!
